# Generated by Django 5.0.6 on 2024-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_booking_check_in_date_alter_booking_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
